version: '3'
services:
  configure:
    build:
      context: .
    command: bash compose_scripts/configure.sh
    volumes:
      - .:/app
  test:
    build:
      context: .
    command: bash compose_scripts/test.sh
    volumes:
      - .:/app
  build:
    build:
      context: .
    command: bash compose_scripts/build.sh
    volumes:
      - .:/app
  fix_ownership:
    build:
      context: .
    command: bash compose_scripts/fix_ownership.sh
    volumes:
      - .:/app