version: '3'
services:
  build_all:
    build:
      context: .
    command: bash compose_scripts/build.sh all
  build_template_repo_c:
    build:
      context: .
    command: bash compose_scripts/build.sh template-repo-c
  configure:
    build:
      context: .
    command: bash compose_scripts/configure.sh
  fix_ownership:
    build:
      context: .
    command: bash compose_scripts/fix_ownership.sh
  memory_check:
    build:
      context: .
    command: bash /app/compose_scripts/memory_check.sh
  test:
    build:
      context: .
    command: bash compose_scripts/test.sh
